# Generated by Django 3.2.15 on 2022-09-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DictApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='part_of_speech',
        ),
    ]
