# Generated by Django 3.2.15 on 2022-09-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictApp', '0003_alter_word_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
